import './globals.css'
import NavBar from './views/navBar/NavBar'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-gradient-to-r from-gray-600 to-slate-800'>
        <NavBar /> 
                {children}
        
        </body>
    </html>
  )
}
